### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by Lalit64** [NvChad/pywal#6]
It wasn't listing chadwal in the list of themes and I tried running the python script seperately and I got this
<img width="864" alt="Screenshot 2024-09-11 at 11 20 00" src="https://github.com/user-attachments/assets/75c6e398-77ba-4882-899e-c58a0fbe2ffa">

**Comment by siduck** [comment]
@Axenide

**Comment by Axenide** [comment]
Hi @Lalit64, which OS are you using?

**Comment by Lalit64** [comment]
@Axenide macOS sonoma 14.5

**Comment by siduck** [comment]
@Lalit64  have you done lazy sync?

**Comment by siduck** [comment]
https://github.com/NvChad/base46/commit/9b81403ef6e29a70bffb7990a0f3dbe5f6095047

**Comment by Lalit64** [comment]
> @Lalit64 have you done lazy sync?

Yeah

**Comment by Axenide** [comment]
Hi @Lalit64, sorry for the delay. The problem you see is because inotify isn't available in MacOS. It is a crucial part of this script since it monitors when `magick` runs to set the theme.

I assume this won't work on Windows either

Later this week I will adapt the script to make it compatible with both MacOS and Windows and I'll let you know.

Thank you for pointing this out!

**Comment by Lalit64** [comment]
@Axenide ok thanks

**Comment by Lalit64** [comment]
@Axenide any updates

**Comment by siduck** [comment]
axenide doesnt probably use macos so he doesnt know, bring forth an alternative!

**Comment by Axenide** [comment]
@Lalit64 done! Sorry for the delay, I just finished my exams in uni. Hope you can give it a try. :)
I'll close the issue, feel free to reopen it if needed.
